### ISSUE TITLE
reCaptcha

### ISSUE THREAD

**Issue by eshevlyakova** [torin-asakura/misik#105]
### С чем связан запрос на фичу?

Подключение reCaptcha 3

### Расскажите как вы это себе видите

С помощью этой библиотеки — https://github.com/t49tran/react-google-recaptcha-v3 подключить капчу к сайту. Отправлять форму, только в случае ее прохождения

**Comment by eshevlyakova** [comment]
@TorinAsakura 

1) Верно ли указан ключ сайта для 3 версии капчи?
2) Добавлен ли домен localhost на стороне сервиса Google Developers?

**Comment by TorinAsakura** [comment]
> @TorinAsakura
> 
> 1. Верно ли указан ключ сайта для 3 версии капчи?
> 2. Добавлен ли домен localhost на стороне сервиса Google Developers?

Добавил localhost

**Comment by eshevlyakova** [comment]
@TorinAsakura 
### Скоуп

Использование библиотеки React Google Recaptcha V3

### Описание

Капча по умолчанию отображается, но со стилями fixed, а не в контейнере. Но как только я указываю пропс container (передаю строку с id нужного Box, в котором капча должна отображаться) к GoogleReCaptchaProvider при открытии модального окна появляется ошибка (скрин). С этой ошибкой я сталкивалась до этого, и мы выяснили, что библиотека не подключилась к google recaptcha. Сейчас она вроде как подключается (скрин)
Контейнер для капчи создается (скрин). 
Не могу понять почему при добавлении пропса библиотека перестает подключаться к google recaptcha. Так как этот код работает для другого проекта, предполагаю, что возможно причина в контексте. Но из-за чего именно не понимаю

### Контекст

[Компонент GoogleReCaptchaProvider](https://github.com/torin-asakura/misik/blob/feat/connecting-recaptcha/ui/form/src/form.component.tsx#L88)
[Box с id](https://github.com/torin-asakura/misik/blob/feat/connecting-recaptcha/ui/form/src/form.component.tsx#L165)


### Воспроизведение

1. В консоли в корне проекта запускаем: `yarn workspace @landing/app run dev`
2. Нажимаем на кнопку "Получить консультацию"

### Ожидаемое поведение

Капча работает и отображается внутри дива с нужным id

### Медиа материалы

<img width="873" alt="Снимок экрана 2023-04-05 в 14 45 28" src="https://user-images.githubusercontent.com/79781486/230070899-ac90249b-0f06-4885-bb32-7985e6366516.png">
<img width="481" alt="Снимок экрана 2023-04-05 в 15 16 30" src="https://user-images.githubusercontent.com/79781486/230077619-92e3ea0a-184b-4f78-bba0-7ae2e2b77d27.png">
<img width="487" alt="Снимок экрана 2023-04-05 в 14 44 37" src="https://user-images.githubusercontent.com/79781486/230070756-33337e8c-e217-432e-8562-0aee82701a0c.png">

### Вопрос

1. Может ли возникать ошибка из-за контекста кода?

**Comment by TorinAsakura** [comment]
Я не вижу отладочной информации. Чтобы ответить на твой вопрос, нужно понять, что происходит с исполняемой областью до - и - в момент маунта. Как только ты соберёшь эти данные с обоих проектов и сравнишь - сможешь получить ответ на свой вопрос.
