### ISSUE TITLE
Сборник ошибок в релизе

### ISSUE THREAD

**Issue by vodopmi** [torin-asakura/misik#107]
### Описание бага

- [x] ссылка на https://misik.pro/relocation везде 500
- [x] текст в услугах наезжает на кнопку в блоках услуг 
- [x] лишние пробелы в текстах "больших" услуг
- [x] неправильная ширина блока "услуги" и "контакты" (у меня на ширине 1440 этои блок уже остальных, возможно, это причина второго бага)

### Воспроизведение

Актуальный релиз

### Ожидаемое поведение

2. Динамическое расстояние между описанием и кнопкой – хорошо. но должен быть задан минимум = 32px

### Материалы

3. 
<img width="1440" alt="Screenshot 2023-06-09 at 16 51 11" src="https://github.com/torin-asakura/misik/assets/102182195/323c26c4-3bbe-4a1d-bf73-cb8add33b7b6">

4.
<img width="1440" alt="Screenshot 2023-06-09 at 17 16 12" src="https://github.com/torin-asakura/misik/assets/102182195/81d2061c-93b1-42fe-9948-dc1f41718ff2">
<img width="1440" alt="Screenshot 2023-06-09 at 17 17 32" src="https://github.com/torin-asakura/misik/assets/102182195/8ea8dcf9-87bf-495f-91a7-e60d5336143a">

https://www.figma.com/file/rk2ELp7UFqqvYJgfC07o6W/Misik-%7C-Web-site?type=design&node-id=250%3A2&t=4gcZbcphfm3SZJXU-1

### Данные окружения

- MacOS@13.4 (22F66)
- Safari@16.5 (18615.2.9.11.4)

**Comment by vodopmi** [comment]
лишние пробелы (3) удалось пофиксить.
- нашёл нужный тип записи в админке
- привёл форматирование в соотвествии с примером)) (удалил обычные переносы строк)
<img width="299" alt="Screenshot 2023-06-09 at 17 33 19" src="https://github.com/torin-asakura/misik/assets/102182195/927d10ce-da1b-4acc-9ec7-d5bca08b95c5">

**Comment by TorinAsakura** [comment]
в общий план по рефактору ВПшек нужно добавить нашего Бориса Владимировича
