### ISSUE TITLE
3D элементы в дизайне

### ISSUE THREAD

**Issue by Nelfimov** [torin-asakura/misik#113]
### С чем связан запрос на фичу?

Необходимо обновить дизайн, дополнив 3D элементами.

### Расскажите как вы это себе видите

Таска дизайнеров с описанием: https://github.com/atls-design/planning/issues/158
ПР с файлами: https://github.com/atls-design/design/pull/9
- [ ] по завершению таски протестировать билд версию

**Comment by Amiditin** [comment]
@pussypistolss добавил модельки на сайт, освещение попробовал сам поставить, если не подходит, то можем созвониться как в прошлый раз.

<details>

[Запись экрана от 01.02.2024 20:19:55.webm](https://github.com/torin-asakura/misik/assets/80476878/a0867853-b51b-419b-af54-0f43ebac5e14)

</details>

**Comment by Amiditin** [comment]
@eantdz обновил ветку, по идее, также как и в `dream-team` assets нужно в cdn выгрузить:
https://github.com/torin-asakura/misik/tree/32ca9f77908e089b7750c5ca6149ecdd33558480/ui/3d-elements/assets

**Comment by Nelfimov** [comment]
Пока непонятно - вроде `nextjs` должен смочь передать файлы до 1мб клиенту. Надо пробовать.

Если будут опять ошибки - отдадим CDN
