### ISSUE TITLE
Adaptive grid

### ISSUE THREAD

**Issue by TFK70** [torin-asakura/misik#17]
## Задача

Адаптировать верстку под более маленькие разрешения

## Что сейчас не так

[Сайт](https://misik.pro)

[Дизайн](https://www.figma.com/file/rk2ELp7UFqqvYJgfC07o6W/Misik-%7C-Web-site?node-id=250%3A2)

- [ ] У блока "Формат работы" при сжатии экрана по ширине появляется избыточный отступ слева, которого быть не должно
![image](https://user-images.githubusercontent.com/62806448/148807351-5a2332ba-f273-4550-b02e-59341cec908c.png)

- [ ] У блока с формой обратной связи нету отступов по бокам при сжатии экрана по ширине

![image](https://user-images.githubusercontent.com/62806448/148807434-03bdda15-2425-4504-8989-2e96bce7f669.png)

**Comment by TorinAsakura** [comment]
+

**Comment by TFK70** [comment]
Resolves by https://github.com/torin-asakura/misik/issues/21
