### ISSUE TITLE
Переделать spy scroll c intersection observer

### ISSUE THREAD

**Issue by TFK70** [torin-asakura/misik#19]
### Проблема

Сейчас на сайте есть spy-scroll, но при определенных сценариях он ведет себя некорректно. Это можно разрешить используя IntersectionObserver, чтобы не писать этот механизм с нуля, как это сделано сейчас.

### Принцип

Конкретно в нашем случае IntersectionObserver будет использоваться для отслеживания появления элемента на экране. Как только определенный блок появляется на экране - обновляется состояние индикатора текущего шага.

### Материалы

[Документация](https://developer.mozilla.org/ru/docs/Web/API/Intersection_Observer_API) по IntersectionObserver

[Пример инициализации](https://github.com/YouThinkResearch/web/blob/master/ui/intersection-observer/src/hooks/use-intersection-observer.hook.ts) и [пример использования](https://github.com/YouThinkResearch/web/blob/master/landing/fragments/landing-easy-start/src/landing-easy-start.component.tsx#L22) IntersectionObserver "в бою"

**Comment by brusselboy** [comment]
## Проблема в передаче пропсов в компонент
[здесь](https://github.com/torin-asakura/misik/pull/20/files#diff-abdef7cf2a94291ab0d015a4e269e9882e193c6b16ad9f0a662554791aceb40aR41-R46) передаю айдишники в компоненты, в этих [компонентах](https://github.com/torin-asakura/misik/pull/20/files#diff-fa78cc3c29735a1d09c35f366d633f1e84229ee27ef6c948fdb2522f235a0dd6) (рассмотрим на примере Services) оборачиваю всё содержимое в forwardRef и заменяю у [ref](https://github.com/torin-asakura/misik/pull/20/files#diff-fa78cc3c29735a1d09c35f366d633f1e84229ee27ef6c948fdb2522f235a0dd6R41) значение с trapRef на ref который передаётся пропсом. Из-за всех этих манипуляций у меня падают ошибки:
1.
![Снимок экрана от 2022-03-18 20-50-51](https://user-images.githubusercontent.com/35490768/159047230-a16acdc9-1128-4a6a-a431-41b4e8257e26.png)
2.
![Снимок экрана от 2022-03-18 20-51-32](https://user-images.githubusercontent.com/35490768/159047283-d9c2c99c-8f42-4542-a689-f04d6493a793.png)

В чём может быть проблема?

**Comment by TFK70** [comment]
@brusselboy в forwardRef первый аргумент - это props, второй - ref, а ты [первый аргумент](https://github.com/torin-asakura/misik/pull/20/files#diff-64d49358e18098cbeff6ad1dd67967c0f2c2a0bd2dfdaed002de55ec81997f16R19) в котором должны лежать пропсы переименовал в реф и обращаешься как с рефом

**Comment by brusselboy** [comment]
## Проблема с закрашиванием spy-scroll`a
@TFK70 
актуальный [commit](https://github.com/torin-asakura/misik/pull/20/commits/85e00a6b93e640f010ca3de36646418c440011f7)

### Описание 
На данный момент при скролле не закрашивается spy-scroll, сделал также как это реализовано в [YouThink](https://github.com/YouThinkResearch/web/blob/master/landing/fragments/landing-easy-start/src/landing-easy-start.component.tsx#L22). Проверил корректно ли [передаётся](https://github.com/torin-asakura/misik/pull/20/commits/85e00a6b93e640f010ca3de36646418c440011f7#diff-abdef7cf2a94291ab0d015a4e269e9882e193c6b16ad9f0a662554791aceb40aR40-R45) ref в компоненты, рассмотрим на примере компонента Services, в нём сделал console.log(ref)

Результат: 
![Снимок экрана от 2022-03-21 16-09-41](https://user-images.githubusercontent.com/35490768/159258198-43ae1359-274f-4d7c-a9b1-28b14cc76e72.png)

В компоненте index.page [здесь](https://github.com/torin-asakura/misik/pull/20/commits/85e00a6b93e640f010ca3de36646418c440011f7#diff-abdef7cf2a94291ab0d015a4e269e9882e193c6b16ad9f0a662554791aceb40aR28) проверил передаётся только один раз 'hero' и из-за этого в [setActive](https://github.com/torin-asakura/misik/pull/20/commits/85e00a6b93e640f010ca3de36646418c440011f7#diff-abdef7cf2a94291ab0d015a4e269e9882e193c6b16ad9f0a662554791aceb40aR31) передается 1 и больше при скролле не обновляется.

Также вот [компонент](https://github.com/torin-asakura/misik/pull/20/commits/85e00a6b93e640f010ca3de36646418c440011f7#diff-ef3555167d129eb88275d6f9a635f5ef8951784a30feba58d5e431ecfc2be4da) в котором должна отрисовываться полоска которая закрашивает spy-scroll, сделал также как это реализовано в YT.

В чём может быть проблема? То что при скролле не закрашивается полоска, что упустил

**Comment by TFK70** [comment]
@brusselboy 

> На данный момент при скролле не закрашивается spy-scroll

Скринкаст? Какой характер проблемы вообще? Верстка? Логика? Окружение?

> сделал также как это реализовано в [YouThink](https://github.com/YouThinkResearch/web/blob/master/landing/fragments/landing-easy-start/src/landing-easy-start.component.tsx#L22)

Лучше бы дал ссылку на свой код, а не на код в юсинке, потому что я понятия не имею что и где ты сделал так же как в ют

> В компоненте index.page [здесь](https://github.com/torin-asakura/misik/pull/20/commits/85e00a6b93e640f010ca3de36646418c440011f7#diff-abdef7cf2a94291ab0d015a4e269e9882e193c6b16ad9f0a662554791aceb40aR28) проверил передаётся только один раз 'hero' и из-за этого в [setActive](https://github.com/torin-asakura/misik/pull/20/commits/85e00a6b93e640f010ca3de36646418c440011f7#diff-abdef7cf2a94291ab0d015a4e269e9882e193c6b16ad9f0a662554791aceb40aR31) передается 1 и больше при скролле не обновляется.

Это предложение где вообще ни слова не понял: что ты проверил? Что за setActive? Что за 'hero'? Где логи/скринкаст? Почему что-то при скролле должно обновляться?

> Также вот [компонент](https://github.com/torin-asakura/misik/pull/20/commits/85e00a6b93e640f010ca3de36646418c440011f7#diff-ef3555167d129eb88275d6f9a635f5ef8951784a30feba58d5e431ecfc2be4da) в котором должна отрисовываться полоска которая закрашивает spy-scroll, сделал также как это реализовано в YT.

На ют нету ничего подобного

> В чём может быть проблема? То что при скролле не закрашивается полоска, что упустил

Переформулируй проблему, сейчас не могу помочь, слишком мало нужных и много ненужных данных, плюс бОльшая часть инфы зависит от контекста, которого у меня нет

**Comment by brusselboy** [comment]
## У меня не работает spy-scroll
@TFK70 
Характер проблемы логика. Видео снял, чисто чтобы показать, что щас происходит со spy-scroll

https://user-images.githubusercontent.com/35490768/159289421-6e742383-d229-4a5a-bf75-38efab2f5308.mp4

## Не закрашивается spy-scroll

[Здесь](https://github.com/torin-asakura/misik/pull/20/commits/85e00a6b93e640f010ca3de36646418c440011f7#diff-ef3555167d129eb88275d6f9a635f5ef8951784a30feba58d5e431ecfc2be4daR28-R36) отрисовывается spy-scroll.

activeDot и total которые передаются в [пропсах](https://github.com/torin-asakura/misik/pull/20/commits/85e00a6b93e640f010ca3de36646418c440011f7#diff-abdef7cf2a94291ab0d015a4e269e9882e193c6b16ad9f0a662554791aceb40aR48):

- total - это количество компонентов (у нас их 5)

- activeDot - это индекс который берется из хука [useIntersectionObserver](https://github.com/torin-asakura/misik/pull/20/commits/85e00a6b93e640f010ca3de36646418c440011f7#diff-abdef7cf2a94291ab0d015a4e269e9882e193c6b16ad9f0a662554791aceb40aR28). 

Пока писал это, понял что логика которая должна закрашивать spy-scroll в корне не верная, но при этом нету понимания как сделать. Наверно первым стоит задать вопрос - как мне отслеживать сколько элементов проскроллено?

**Comment by TFK70** [comment]
@brusselboy 

> Наверно первым стоит задать вопрос - как мне отслеживать сколько элементов проскроллено?

- useIntersectionObserver работает таким образом, что когда ты спредишь getObserverProps(id) на компонент - этому компоненту присваивается id, который ты передал в аргумент. В сам useIntersectionObserver ты передаешь колбек, который вызывается тогда, когда один из компонентов на которые ты заспредил getObserverProps появляется на экране, при этом передавая первым аргументом id этого самого элемента. То есть мы в состоянии отслеживать когда и какой элемент появляется на экране
- Исходя из предыдущего ты можешь сделать вокруг этого дополнительную логику. Попробуем завести счетчик - когда какой-либо элемент появляется на экране - прибавляем его на единицу. 
- Казалось бы все, но нам нужно еще продумать сценарий когда этот счетчик должен убавляться. Тут все немножко сложнее, потому что IntersectionObserver может отслеживать только появление элемента на экране, а не его исчезание. Это можно обойти следующим образом: тебе нужно где-то хранить id компонентов, которые уже появлялись на экране. Таким образом, когда какой-то элемент появляется на экране во второй раз означает, что пользователь прокрутил вверх, а не вниз, и что счетчик нужно убавить.

**Comment by brusselboy** [comment]
@TFK70 

> В сам useIntersectionObserver ты передаешь колбек, который вызывается тогда, когда один из компонентов на которые ты заспредил getObserverProps появляется на экране, при этом передавая первым аргументом id этого самого элемента. То есть мы в состоянии отслеживать когда и какой элемент появляется на экране

Не совсем понимаю как мне отслеживать то что useIntersectionObserver находится на определенном элементе? Щас делаю console.log(id) этого [id](https://github.com/torin-asakura/misik/pull/20/commits/85e00a6b93e640f010ca3de36646418c440011f7#diff-abdef7cf2a94291ab0d015a4e269e9882e193c6b16ad9f0a662554791aceb40aR28) который приходит с хука, при скролле в логах появляется только hero, это первый элемент, на остальные не реагирует

https://user-images.githubusercontent.com/35490768/159330593-a439b01f-f67e-4820-a9a2-de9ce433fb02.mp4

**Comment by brusselboy** [comment]
## Intersection-observer не реагирует на компонент Services
@TFK70 
По нормальному observer должен реагировать на services если повесить ref на родительский [Box](https://github.com/torin-asakura/misik/pull/20/files#diff-fa78cc3c29735a1d09c35f366d633f1e84229ee27ef6c948fdb2522f235a0dd6R38). Так у меня сделано во всех других компонентах - [пример](https://github.com/torin-asakura/misik/pull/20/files#diff-64d49358e18098cbeff6ad1dd67967c0f2c2a0bd2dfdaed002de55ec81997f16R35) и на них observer реагирует корректно.

## Что сделано на данный момент

Сейчас у меня повешен ref [тут](https://github.com/torin-asakura/misik/pull/20/files#diff-fa78cc3c29735a1d09c35f366d633f1e84229ee27ef6c948fdb2522f235a0dd6R64) для того чтобы проверить что observer вообще хоть на что-то в services при скролле реагирует и в целом это работает, когда доскролливаешь до этого момента spy-scroll закрашивается. Изменение значения у threshold не помогает, если его уменьшать ниже текущего значения (0.6) появляются проблемы. 
В чём может быть проблема?

На видео можно увидеть, как сейчас закрашивается spy-scroll на services, да ref находится не на родительском Box, как в других компонентах, ибо если его повесить на него observer вообще не будет реагировать.

https://user-images.githubusercontent.com/35490768/159772567-ec9ecb4f-6599-4cc7-8840-dbb236aa7bb0.mp4

**Comment by TFK70** [comment]
@brusselboy смотри threshold, services это большой блок, у него threshold свой

**Comment by brusselboy** [comment]
> @brusselboy смотри threshold, services это большой блок, у него threshold свой

А как ему индивидуально treshold изменить?

**Comment by TFK70** [comment]
@brusselboy это уже вопрос к реализации useIntersectionObserver: модифицируй его таким образом, чтобы определенному блоку можно было свой трешхолд задать

**Comment by brusselboy** [comment]
## Не работает useIntersectionObserver
@TFK70 

[Добавил](https://github.com/torin-asakura/misik/pull/20/commits/be9c94d1e6fa6c65aaac96dc943fd2d489d7c18e#diff-abdef7cf2a94291ab0d015a4e269e9882e193c6b16ad9f0a662554791aceb40aR41-R46) threshold там где спредится getObserverOptions

Затем в useIntersectionObserver [сетаю](https://github.com/torin-asakura/misik/pull/20/commits/be9c94d1e6fa6c65aaac96dc943fd2d489d7c18e#diff-4b519a46b396ce2279b4963b25a1ab5830a54bc4f017671bc2ffd3ad2625ed8dR23) threshold в [observerThreshold](https://github.com/torin-asakura/misik/pull/20/commits/be9c94d1e6fa6c65aaac96dc943fd2d489d7c18e#diff-4b519a46b396ce2279b4963b25a1ab5830a54bc4f017671bc2ffd3ad2625ed8dR10), но из-за того что я добавляю одинаковый ключ 0.6 к нескольким компонентам, я получаю два элемента, хотя их должно быть 5. 
console.log(observerThreshold) :
![Снимок экрана от 2022-03-24 21-59-26](https://user-images.githubusercontent.com/35490768/159980599-5fbdbeaa-046d-49f8-a9a6-78bdfd54c451.png)

Специально проверил, поменял значения холда которые спредятся в getObserverOptions на разные вот что получается: 
![Снимок экрана от 2022-03-24 22-01-20](https://user-images.githubusercontent.com/35490768/159980899-6951b809-19ef-42d4-a5dd-5dfb0c97fc33.png)
Как мне это исправить?

**Comment by brusselboy** [comment]
## Передача threshold в ref
@TFK70 
Заменил Map на массив, чтобы можно было хранить одинаковые ключи, теперь коллекция выглядит так:
![Снимок экрана от 2022-03-25 14-07-27](https://user-images.githubusercontent.com/35490768/160100460-d015a097-5ba5-4c93-9b1c-1ae2979c5861.png)
Но не понимаю, как мне threshold передать в ref.
![Снимок экрана от 2022-03-25 14-03-45](https://user-images.githubusercontent.com/35490768/160099879-9def7d6e-cc0f-4645-af52-2d3bb594a64d.png)
В ref у нас лежит current в котором находится поле osberverId, как мне также передать в current трешхолд?

**Comment by brusselboy** [comment]
## Пояснение как щас работает useIntersectionObserver

@TFK70 

Есть [дефолтный](https://github.com/torin-asakura/misik/pull/20/commits/068dd1724f732ce67e1cdb1402b380b6c656c7ff#diff-4b519a46b396ce2279b4963b25a1ab5830a54bc4f017671bc2ffd3ad2625ed8dR31) observer в нем есть [проверка](https://github.com/torin-asakura/misik/pull/20/commits/068dd1724f732ce67e1cdb1402b380b6c656c7ff#diff-4b519a46b396ce2279b4963b25a1ab5830a54bc4f017671bc2ffd3ad2625ed8dR33) которая кстати уже не будет работать, потому что до этого там было сделано с помощью Map и в current было поле thresholdValue по которому можно было проверять соответствует оно дефолтному трешхолду или нет, если нет то срабатывал бы [observerCustom](https://github.com/torin-asakura/misik/pull/20/commits/068dd1724f732ce67e1cdb1402b380b6c656c7ff#diff-4b519a46b396ce2279b4963b25a1ab5830a54bc4f017671bc2ffd3ad2625ed8dR40) в котором также имеется [проверка](https://github.com/torin-asakura/misik/pull/20/commits/068dd1724f732ce67e1cdb1402b380b6c656c7ff#diff-4b519a46b396ce2279b4963b25a1ab5830a54bc4f017671bc2ffd3ad2625ed8dR42), если трешхолд не равен дефолтному значению, тогда в опции передастся кастомный трешхолд 
В целом я щас в тупике и не понимаю, как мне это провернуть с массивом, потому что когда я [перебираю](https://github.com/torin-asakura/misik/pull/20/commits/068dd1724f732ce67e1cdb1402b380b6c656c7ff#diff-4b519a46b396ce2279b4963b25a1ab5830a54bc4f017671bc2ffd3ad2625ed8dR58-R63) элементы [массива](https://github.com/torin-asakura/misik/pull/20/commits/068dd1724f732ce67e1cdb1402b380b6c656c7ff#diff-4b519a46b396ce2279b4963b25a1ab5830a54bc4f017671bc2ffd3ad2625ed8dR10), не знаю как мне [сюда](https://github.com/torin-asakura/misik/pull/20/commits/068dd1724f732ce67e1cdb1402b380b6c656c7ff#diff-4b519a46b396ce2279b4963b25a1ab5830a54bc4f017671bc2ffd3ad2625ed8dL64) передавать трешхолд

**Comment by brusselboy** [comment]
### Проблема
@TFK70 

[Коллекция](https://github.com/torin-asakura/misik/blob/fix/spy-scroll/ui/intersection-observer/src/hooks/use-intersection-observer.hook.ts#L22) Map не будет хранить в себе одинаковые ключи. В [проверке](https://github.com/torin-asakura/misik/blob/fix/spy-scroll/ui/intersection-observer/src/hooks/use-intersection-observer.hook.ts#L27) if если intersectionObserver не содержит threshold, ты [сетаешь](https://github.com/torin-asakura/misik/blob/fix/spy-scroll/ui/intersection-observer/src/hooks/use-intersection-observer.hook.ts#L28) и делаешь [ключом](https://github.com/torin-asakura/misik/blob/fix/spy-scroll/ui/intersection-observer/src/hooks/use-intersection-observer.hook.ts#L29) observerThreshold, но он будет иметь одинаковые значения 0.6 и из-за этого intersectionObservers выглядит так:
![Снимок экрана от 2022-03-26 15-07-50](https://user-images.githubusercontent.com/35490768/160236713-fd9499b3-1ae5-474a-972e-7433cb75d472.png)
