### ISSUE TITLE
Theme research

### ISSUE THREAD

**Issue by TFK70** [torin-asakura/misik#3]
### Резолв путей в бандле

**Проблема:**

Есть бандл сгенеренный с помощью next export, в нем лежит html и js
В html обращение к js файлам в `<script>` происходит относительно корня, т.е.
`<script src="/.next/chunks/file.js"></script>`

Но сам бандл находится внутри темы, поэтому путь до js'ов должен быть такой:
`/wp-content/themes/<тема>/dist/.next/chunks/file.js`

Как можно решить эту проблему средствами WP API без хардкода пути?

### Потенциальное решение проблемы с путями средставим WP API

Еще один вариант: перенос файлов к которым обращаются от корня непосредственно в корень используя [WP Filesystem API](https://codex.wordpress.org/Filesystem_API)

**Минус:** в корне будет еще 1 директория
**Плюс:** используется API вордпресса, так что по сравнению с решением выше оно более надежное

Принцип простой: просто берем все js'ы и прочие файлы к которым обращаются похожим образом: `/.next/.....`
Берем WP Filesystem API и с его помощью перемещаем эти файлы в корень, чтобы не пришлось менять сами пути

**Comment by TorinAsakura** [comment]
Самый простой вариант -  при экспорте в ci указываешь нужный url и все должно подхватываться автоматом
через nginx https://serverfault.com/questions/607091/nginx-rewrite-urls-but-not-static-files
