### ISSUE TITLE
Страница с новой услугой

### ISSUE THREAD

**Issue by TFK70** [torin-asakura/misik#44]
### Задача

Сверстать [страницу](https://www.figma.com/file/rk2ELp7UFqqvYJgfC07o6W/Misik-%7C-Web-site?node-id=2299%3A1298) с услугой переезда в США

**Comment by brusselboy** [comment]
## Не работает прогресс бар

@TFK70 

### Описание
У drawer есть [прогресс бар](https://www.figma.com/file/rk2ELp7UFqqvYJgfC07o6W/Misik-%7C-Web-site?node-id=2356%3A3680), сейчас он не реагирует на скролл. 

### Шаги воспроизведение

1. `yarn workspace @landing/app dev`
2. `localhost:3000/relocation`
3. Доскроллить до блока КАК ПЕРЕЕХАТЬ В АМЕРИКУ
4. Нажать на кнопку **описание услуги**
5. Откроется drawer и если в нём поскроллить, видно что прогресс бар не работает

### Материалы

Вся логика находится в [usePercent](https://github.com/torin-asakura/misik/blob/feat/services-page/ui/drawer/src/progress-bar/use-percent.hook.ts)

<details>

```tsx
const usePercent = () => {
  const [scrollPercent, setScrollPercent] = useState<number>(0)

  let drawerElement = document.documentElement

  setTimeout(() => {
    drawerElement = document.getElementById('drawer')!
  }, 100)

  useEffect(() => {
    const handleScroll = () => {
      const winScroll = drawerElement!.scrollTop
      const height = drawerElement!.scrollHeight
      const percent = (winScroll / (height - drawerElement.clientHeight)) * 100

      setScrollPercent(percent)
    }

    drawerElement.addEventListener('scroll', handleScroll, { passive: true })

    return () => drawerElement.removeEventListener('scroll', handleScroll)
  }, [drawerElement])

  return scrollPercent
}
```

</details>

Нам нужно высчитывать высоту самого drawer и сколько осталось проскроллить, вся проблема в логике функции `handleScroll`, которая неверно высчитывает. 

Допустим если если сделать так со всей страницей:

```tsx
 const percent = (window.scrollY / (document.body.scrollHeight - window.innerHeight)) * 100
```
Процент будет высчитываться от 0 до 100, но с отдельным элементом в виде drawer такое сделать не выходит. 


### Вопрос
Как можно видоизменить функцию handleScroll, чтобы прогресс бар работал корректно?

**Comment by TFK70** [comment]
@brusselboy ты пробовал так делать?

https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp

**Comment by brusselboy** [comment]
> @brusselboy ты пробовал так делать?
> 
> https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp

Полоса должна закрашиваться

**Comment by TFK70** [comment]
@brusselboy почему? Тогда бы initial state был бы как в спай скролле - полоска была бы пустой, а то что у тебя в дроуере - это скролл бар, черная штучка - это ползунок

**Comment by brusselboy** [comment]
> @brusselboy почему? Тогда бы initial state был бы как в спай скролле - полоска была бы пустой, а то что у тебя в дроуере - это скролл бар, черная штучка - это ползунок

[spy-scroll](https://www.figma.com/file/rk2ELp7UFqqvYJgfC07o6W/Misik-%7C-Web-site?node-id=1636%3A1666) initial state не пустой, то-что в drawer 154% такой же спай скролл, только здесь именно на сам скролл должна полоска реагировать, а не на блоки

https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp это заменяет браузерный скроллбар, это же совсем не то что нужно, это также можно понять потому, как он расположен, полоска находится аккурат под Close icon, браузерный там никак не появится

**Comment by brusselboy** [comment]
@TFK70 грубо говоря вот эта черная полоска это то что уже проскроллено (видимая область, так же как в index page), а то что не закрашено, можно закрасить путём скроллинга

**Comment by TFK70** [comment]
@brusselboy https://www.figma.com/file/rk2ELp7UFqqvYJgfC07o6W?node-id=2356:3589#231867560

Этог скроллбар, а на все что ты говоришь можно найти кучу хаков в гугле

https://www.figma.com/file/rk2ELp7UFqqvYJgfC07o6W?node-id=2356:3589#231867560
