### ISSUE TITLE
Карусели

### ISSUE THREAD

**Issue by TFK70** [torin-asakura/misik#57]
### Проблемы

- [ ] На меньших разрешениях такая полоса появляется.

![image](https://user-images.githubusercontent.com/62806448/180985095-5ba501a7-d8db-484c-a1bc-b0f6bf817371.png)

- [ ] В мобилке текст пропал.

![image](https://user-images.githubusercontent.com/62806448/180985207-69e0ad89-f164-41d7-ad5a-f930b3bfab10.png)

**Comment by brusselboy** [comment]
### Описание проблемы

@TFK70 

1. Полоса появляется не из-за карусели с партнерами, а карусель c направлением работ здесь никакой роли не играет
2. Первый фактор который влияет на белую полосу, проще говоря из-за чего вываливается весь контент вправо на малых разрешениях - из-за отступа 430px слева
<details>

![image](https://user-images.githubusercontent.com/35490768/180798624-ea0b9f80-dece-4a66-9ee4-c24cca5205a9.png)

</details>

Если убрать карусель, а отступ слева оставить, полосы нет

<details>

![image](https://user-images.githubusercontent.com/35490768/180799375-b01d55b6-049c-4f45-b508-1b96218f41f3.png)

</details>

3. Второй фактор который также влияет на вываливание контента - это сам контент (тайтл и описание), НО главное условие из-за чего контент вываливается - это отступ слева

<details>

![image](https://user-images.githubusercontent.com/35490768/180800503-9d27209a-8386-4af3-a752-40d4f331b371.png)

</details> 

4. Так выглядит на малых разрешениях если убрать minWidth в 430px 

<details>

![image](https://user-images.githubusercontent.com/35490768/180801906-ff209fcc-70c1-4e55-93e6-3bf46510dda5.png)

</details>

### Итог

Я считаю что проблема именно в  этом отступе слева, вот он [в коде](https://github.com/torin-asakura/misik/blob/master/landing/about-fragment/src/about.component.tsx#L49), вываливание контента при такой логике неизбежно из-за заданной минимальной ширины в 430px. 

Да и вообще в целом на малых разрешениях сайт теперь выглядит перекошенным вправо из-за этих отступов.

**Comment by TFK70** [comment]
@brusselboy нет, отступ тут совсем не при чем, проблема именно в каруселях. Ты можешь убрать абсолютно все карусели с сайта и белой полосы не будет, так как все остальные элементы на странице у тебя флексятся, а карусели - нет

В таком случае просто напиши комментом как это воспроизвести и пока оставь, это системная проблема

**Comment by brusselboy** [comment]
@TFK70 убрал все карусели, полоса на таком же разрешении остается

https://user-images.githubusercontent.com/35490768/180805459-f84fb310-3408-40f0-93e4-facb41e2adb1.mp4

**Comment by TFK70** [comment]
@brusselboy а если убрать min-width то белая полоса вообще нигде и никак не появляется? Ни на каком разрешении?

**Comment by brusselboy** [comment]
> @brusselboy а если убрать min-width то белая полоса вообще нигде и никак не появляется? Ни на каком разрешении?

Из компонента about в таком случае ничего не вываливается вплоть до таблет размеров, там уже из другого скоупа появляются проблемы (компонент фидбек) и по-моему всё тот же отступ слева 

![image](https://user-images.githubusercontent.com/35490768/180806991-a9edcb39-0eee-4647-97f9-6c774921c010.png)

**Comment by TFK70** [comment]
@brusselboy это происходит потому что где-то есть блок с фиксированной шириной

Найди его, локализуй проблему, сообщи что это за блок и пофикси

**Comment by brusselboy** [comment]
## Белая полоса справа
@TFK70 
### Описание
Появляется из-за большого контента, который рассчитан для больших десктоп разрешений, к тому же ситуацию усугубляет отступ слева с минимальным значением в 430px, который вытесняет элементы вправо - итог: получаем белую полосу

#### Примеры большого контента на малых десктоп разрешениях:
<details>

![image](https://user-images.githubusercontent.com/35490768/180824771-020307b4-3fe5-4400-b0ac-f1d1926acd29.png)

</details>

<details>

![image](https://user-images.githubusercontent.com/35490768/180825325-e6574dad-4aa7-4221-b222-4cf71a1dd712.png)

</details>
