### ISSUE TITLE
Добавить description на страницах

### ISSUE THREAD

**Issue by TFK70** [torin-asakura/misik#67]
### Задача

Добавить [description](https://wiki.rookee.ru/meta-teg-description/) теги на всех страницах

**Comment by brusselboy** [comment]
@TFK70 текст для дескрипшнов брать из заголовков в hero?

<details>

<img width="974" alt="image" src="https://user-images.githubusercontent.com/35490768/182122987-641904c6-3f98-4093-b5cb-89f50bde92b8.png">

</details>

Для главной это будет **Оказываем юридическую помощь в сфере IT** 
Для переезда в сша **Ваша программа переезда в США**

Правильно понимаю?

**Comment by TFK70** [comment]
> @TFK70 текст для дескрипшнов брать из заголовков в hero?
> 
> Для главной это будет **Оказываем юридическую помощь в сфере IT** Для переезда в сша **Ваша программа переезда в США**
> 
> Правильно понимаю?

да
