### ISSUE TITLE
Ссылка на наш фронт в админке

### ISSUE THREAD

**Issue by TFK70** [torin-asakura/misik#71]
### Проблема

Когда мы ставим ссылку на наш фронт (https://misik.pro/) в [админке](https://wp.misik.pro/wp-admin/options-general.php) мы не можем обновлять записи, пропадают featured image у записей

При этом мы не можем оставить в админке ссылку на фронт https://wp.misik.pro/ так как она индексируется вместе со всем остальным сайтом, а фронт на ней битый

### Материалы

![telegram-cloud-photo-size-2-5406588786386779439-y](https://user-images.githubusercontent.com/62806448/181218080-06ef1967-563a-4e4b-aa2e-004e5a6a2bc9.jpg)

**Comment by TorinAsakura** [comment]
Не актуально, так как API давно вынесено на отдельный поддомен
