### ISSUE TITLE
Навигация

### ISSUE THREAD

**Issue by TFK70** [torin-asakura/misik#74]
## Навигация

- [x] Правый блок явно нестабилен, его контент больше чем сам контейнер и почему-то спозиционирован абсолютно, из-за чего при работе с Drawer'ом возникают проблемы. Или же это проблема автолэйатинга, надо разбираться. Смотри инспектор.

![image](https://user-images.githubusercontent.com/62806448/181740545-2a187a63-cb74-4f4a-ac9d-e09d14c918bb.png)

- [x] ScrollNav не соответствует дизайну. Отступ между лейблом и баром должны быть 48х, у нас 32рх. Контейнер для текста выглядит нестабильным, так как его высота (на момент ревью 333рх) не соответствует контенту. Вероятно очередные проблемы неправильного использования автолэйаутов.
- [x] У блоков-разделителей нет высот, из-за чего их тупо не видно в испекторе. Как пример - блок между логотипом и элементами меню.

**Comment by brusselboy** [comment]
## Проблема с spy-scroll
@TFK70 

### Описание
Сейчас текст выравнивается по центру, а должен быть выровнен к нижнему краю (по сути выровнен по левому краю). Из-за этого существующий отступ на текст никак не влияет

### Материалы

Два скрина по которым можно увидеть что текст выровнен по центру (услуги должны быть ближе к нижнему краю):

<details>

<img width="116" alt="image" src="https://user-images.githubusercontent.com/35490768/182451314-405d3351-6cb0-48ba-b49e-25926ef2e151.png">

<img width="116" alt="image" src="https://user-images.githubusercontent.com/35490768/182451338-1f02b8d3-5bac-47d2-a536-824aa3942486.png">

</details>

Сейчас попробовал заменить [textAlign](https://github.com/torin-asakura/misik/blob/fix/finalize-layout/ui/spy-scroll/src/step-display/step-display.component.tsx#L17) на `verticalAlign: 'text-bottom'` , не помогло

### Вопрос

Как прижать текст к бару?

**Comment by brusselboy** [comment]
## Баг с навигацией

@TFK70 

### Описание
Задача - нужно чтобы при скролле вниз навигация скрывалась, при скролле вверх навигация появлялась. Все сделал, но есть баг, при загрузке страницы `scrollY` всегда равен 0 и не обновляется. Самое интересное заключается в том, что если уменьшить экран, допустим панелью разработчика или перейти в dimensions режим и перезапустить страницу, то все работает и `scrollY` обновляется когда скроллишь.

Прогуглил свою проблему с `scrollY` который всегда равен 0, вот что нашел:
- [ответ 1](https://overcoder.net/q/2991659/scrolly-scrolltop-%D0%BD%D0%B5-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82-%D0%BA%D0%BE%D0%B3%D0%B4%D0%B0-%D0%B2%D1%8B%D1%81%D0%BE%D1%82%D0%B0-html-%D0%B8-body-%D1%80%D0%B0%D0%B2%D0%BD%D0%B0-100)
- [ответ 2](https://ru.stackoverflow.com/questions/1309489/%D0%9D%D0%B5-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82-window-scrolly)
- [ответ 3](https://stackoverflow.com/questions/41391907/element-scrolltop-always-returns-0)

Ни одно решение не помогло.

### Материалы

Сам [код](https://github.com/torin-asakura/misik/blob/fix/finalize-layout/landing/fragments/landing-navigation/src/navigation.component.tsx#L37-L56)

<details>

```tsx
  const [scrollHeight, setScrollHeight] = useState<number>(0)

  const prevScrollHeightRef = useRef<number | null>(null)

  const prevScrollHeight = prevScrollHeightRef.current

  const handleScroll = () => {
    const scrollPosition =
      (window.scrollY / (document.body.scrollHeight - window.innerHeight)) * 100

    setScrollHeight(scrollPosition)
  }

  useEffect(() => {
    prevScrollHeightRef.current = scrollHeight
  }, [scrollHeight])

  useEffect(() => {
    document.addEventListener('scroll', handleScroll, { passive: true })

    return () => document.removeEventListener('scroll', handleScroll)
  }, [])

.....

<Box
          width='100%'
          position='fixed'
          height={88}
          top={scrollHeight > prevScrollHeight! ? -100 : 0}
          backgroundColor={isMobileNav ? 'white' : 'transparent'}
          style={{ transition: '0.4s' }}
>

```

</details>

#### Видео
Дефолтное экран

https://user-images.githubusercontent.com/35490768/183392162-d5040b4c-74e9-438c-ad35-bf8733f26c3d.mp4

C dimensions, либо если просто открыть панель разработчика

https://user-images.githubusercontent.com/35490768/183392518-a7562816-6aa3-44ee-9a03-a4a4fa40bbe7.mp4

### Вопрос

В чём может быть проблема, то что в dimensions все работает и scrollY обновляется, а при дефолтном экране scrollY всегда равен 0 из-за этого не работает навигация

**Comment by TFK70** [comment]
@brusselboy потому что нативный скролл блокирует либа locomotive scroll (но, как ты уже заметил, делает она это только на десктопе, на мобилке скролл остается нативным)

Оставь тогда это пока, я потом сделаю
