### ISSUE TITLE
Hero

### ISSUE THREAD

**Issue by TFK70** [torin-asakura/misik#76]
## Hero:
- [x] CTA так и не пофикшен
- [x] Отступы блоков не соответствуют дизайну, достаточно посмотреть на отступ текста в hero от контейнера ScrollNav. Должно быть 317, а по факту 295.
- [x] По задумке, карусель имеет "сквозной" дизайн, сейчас всё ещё имеются отступы.
- [x] Разделительная линия (дивайдер) должна быть 100% ширины.

**Comment by brusselboy** [comment]
## Проблема с позиционированием на мобильных устройствах бэкграунда на странице Relocation
@dakand 

### Описание
Чтобы спозиционировать [бэкграунд на мобилках](https://www.figma.com/file/rk2ELp7UFqqvYJgfC07o6W/Misik-%7C-Web-site?node-id=2380%3A4162), за основу берется [бэкграунд с десктопа](https://www.figma.com/file/rk2ELp7UFqqvYJgfC07o6W/Misik-%7C-Web-site?node-id=2299%3A1299), мы не разделяем бэкграунд на десктоп и мобилку, в таком случае пришлось бы с сервера запрашивать две разные картинки. 

Также реализовано на [главной странице](https://www.figma.com/file/rk2ELp7UFqqvYJgfC07o6W/Misik-%7C-Web-site?node-id=1503%3A1112), то есть имеется одна картинка с десктопа и она же используется на мобилке и при этом нет проблем с позиционированием, если посмотреть на проде десктоп версию и мобайл версию, там бэкграунд будет как в дизайне. 

### Материалы

- Так выглядит бэкграунд на мобилке если пытаться адаптировать десктопную версию:

<details>

![image](https://user-images.githubusercontent.com/35490768/183884651-2a11b6bc-41cc-4687-a483-4771c6e53735.png)

</details>

- Так выглядит если придерживаться логике которая реализована на главной странице:

<details>

<img width="566" alt="image" src="https://user-images.githubusercontent.com/35490768/183884893-b75ac7c7-8233-47da-854b-a37d4ed1c1c3.png">

</details>

### Отсюда два вопроса:
1. Правильно ли я понимаю что на текущий момент в дизайне на странице релокейта подразумевается один бэкграунд, но в итоге получилось два разных (т.к десктоп некорректно растягивается на мобилке)?
2. Возможно ли в дизайне адаптировать бэкграунд на мобильной версии? (сделать также как это сделано на главной странице)
