### ISSUE TITLE
О нас

### ISSUE THREAD

**Issue by TFK70** [torin-asakura/misik#77]
## О нас:
- [x] Анимация внутри контейнера со стеллой не позиционируется относительно родителя, из-за чего происходит перегрузка (это когда контент вылезает за пределы блока) из-за чего создаётся неверный отступ слева.
- [x] Отступ справа не соответствует дизайну, или это проблема не соответствия контента дизайну, надо смотреть.

**Comment by brusselboy** [comment]
## Несоответствие отступов с дизайном по бокам 

@TorinAsakura @TFK70 

### Описание

По дизайну отступ слева на десктопе составляет 430px и справа 280px при разрешении 1920x1080. Если же их сделать такими, то на меньших десктопных разрешениях при таких отступах будут проблемы с вываливанием контента. Весь контент проверил он соответсвует ширине как в дизайне, но почему то флексы немного сжирают отступы и вместо 430px слева это 410px и вместо 280px слева это 266px. Из-за чего флексы так делают не понятно, делать их фиксированными не вариант, как написал на меньших разрешениях будут проблемы.

### Материалы
Не фиксированный отступ слева в 430px
<details>

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/35490768/182099441-f1c23be8-3588-4ca2-9b31-c0dce1649a5c.png">

</details>

Не фиксированный отступ справа в 280px

<details>

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/35490768/182105640-a782aa64-c018-402b-9d7b-58bf89d096c6.png">

</details>

Пример того что происходит с фикс отступами слева и справа на меньших десктоп разрешениях:

<details>

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/35490768/182106149-13166d08-13bd-4c24-accc-e6487f2a9715.png">

</details>

### Вопрос 

Оставляем динамические отступы? но в таком случае на 1920х1080 будут не по дизайну. Либо делаем фиксированными, но это будет уродливо смотреться

**Comment by brusselboy** [comment]
## Баг со стелой
@TFK70  

### Описание

Анимационный элемент у стелы имеет разные размеры на десктопе и мобилке. Чтобы это реализовать отображаю с помощью `display` айтем для десктопа и для мобилки с нужными размерами, но из-за чего то пропадает шар внутри круга на мобилке

### Материалы

[Код иконки](https://github.com/torin-asakura/misik/blob/fix/finalize-layout/landing/fragments/landing-about/src/icons/misik-law.icon.tsx)

[Вертска](https://github.com/torin-asakura/misik/blob/fix/finalize-layout/landing/fragments/landing-about/src/about.component.tsx#L62-L71)

```tsx

<Layout display={['none', 'none', 'flex']}>
    <Box position='absolute' top='30%' left={-16}>
       <MisikLawIcon width={141} height={141} />
    </Box>
</Layout>
<Layout display={['flex', 'flex', 'none']}>
    <Box position='absolute' top='30%' left={-10}>
      <MisikLawIcon width={96} height={96} />
    </Box>
</Layout>
```

Mobile:
<details>

<img width="503" alt="image" src="https://user-images.githubusercontent.com/35490768/182109015-b08b7c2a-2e93-498b-96e8-ecd7fa0c3e6d.png">

</details>

Desktop:
<details>

<img width="1191" alt="image" src="https://user-images.githubusercontent.com/35490768/182109675-f775c123-1a5f-431a-8f6e-50ce3c7c4c3c.png">

</details>

### Вопрос

Из-за чего это может быть?
