### ISSUE TITLE
Добавить кластеры на карту

### ISSUE THREAD

**Issue by TFK70** [torin-asakura/misik#94]
### Задача

Собрать маркеры в России в кластер на большом масштабе

**Comment by TorinAsakura** [comment]
Также, рекомендую поправить масштаб при инициализации. На текущем почти незаметна точка в США

Примерно такой масштаб будет хорошо показывать обе локации
![Снимок экрана 2022-08-13 в 11 20 31](https://user-images.githubusercontent.com/3940885/184475618-5cf302aa-3585-4313-aaf5-1b54febec570.png)
