### ISSUE TITLE
reCaptcha

### ISSUE THREAD

**Issue by TorinAsakura** [torin-asakura/misik#96]
### С чем связан запрос на фичу?

Чуть меньше суток назад наши сайты были атакованы спам-рассылкой которая длилась почти 20 часов 

### Расскажите как вы это себе видите

Я завёл для сайта Misik reCaptcha у Google и добавил проверку рекаптчи в форму.
Тебе надо ожидать прохождение каптчи перед отправкой формы.

**Comment by carminio** [comment]
@TFK70 

Нужна помощь с капчей, [прикрутить](https://github.com/torin-asakura/misik/blob/master/ui/form/src/form.component.tsx) прикрутил, но не отображается

**Comment by TorinAsakura** [comment]
@carminio какого рода помощь? Что ты дал ссылку на компонент? Куда смотреть? Как воспроизвести? Ну, что, учить тебя оформлять запросы?

**Comment by carminio** [comment]
https://github.com/torin-asakura/misik/pull/104 completed
